In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
import scipy
from scipy.signal import resample, find_peaks 
import warnings
warnings.filterwarnings('ignore')



In [2]:
data = pd.read_csv("train.csv")
data.head(10)

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  tBodyAcc-std()-X  \
0           0.288585          -0.020294          -0.132905         -0.995279   
1           0.278419          -0.016411          -0.123520         -0.998245   
2           0.279653          -0.019467          -0.113462         -0.995380   
3           0.279174          -0.026201          -0.123283         -0.996091   
4           0.276629          -0.016570          -0.115362         -0.998139   
5           0.277199          -0.010098          -0.105137         -0.997335   
6           0.279454          -0.019641          -0.110022         -0.996921   
7           0.277432          -0.030488          -0.125360         -0.996559   
8           0.277293          -0.021751          -0.120751         -0.997328   
9           0.280586          -0.009960          -0.106065         -0.994803   

   tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  tBodyAcc-mad()-Y  \
0         -0.983111         -0.913526         -0.995112         -0.983185   
1         -0.975300         -0.960322         -0.998807         -0.974914   
2         -0.967187         -0.978944         -0.996520         -0.963668   
3         -0.983403         -0.990675         -0.997099         -0.982750   
4         -0.980817         -0.990482         -0.998321         -0.979672   
5         -0.990487         -0.995420         -0.997627         -0.990218   
6         -0.967186         -0.983118         -0.997003         -0.966097   
7         -0.966728         -0.981585         -0.996485         -0.966313   
8         -0.961245         -0.983672         -0.997596         -0.957236   
9         -0.972758         -0.986244         -0.995405         -0.973663   

   tBodyAcc-mad()-Z  tBodyAcc-max()-X  ...  fBodyBodyGyroJerkMag-kurtosis()  \
0         -0.923527         -0.934724  ...                        -0.710304   
1         -0.957686         -0.943068  ...                        -0.861499   
2         -0.977469         -0.938692  ...                        -0.760104   
3         -0.989302         -0.938692  ...                        -0.482845   
4         -0.990441         -0.942469  ...                        -0.699205   
5         -0.995549         -0.942469  ...                        -0.844619   
6         -0.983116         -0.940987  ...                        -0.564430   
7         -0.982982         -0.940987  ...                        -0.421715   
8         -0.984379         -0.940598  ...                        -0.572995   
9         -0.985642         -0.940028  ...                         0.140452   

   angle(tBodyAccMean,gravity)  angle(tBodyAccJerkMean),gravityMean)  \
0                    -0.112754                              0.030400   
1                     0.053477                             -0.007435   
2                    -0.118559                              0.177899   
3                    -0.036788                             -0.012892   
4                     0.123320                              0.122542   
5                     0.082632                             -0.143439   
6                    -0.212754                             -0.230622   
7                    -0.020888                              0.593996   
8                     0.012954                              0.080936   
9                    -0.020590                             -0.127730   

   angle(tBodyGyroMean,gravityMean)  angle(tBodyGyroJerkMean,gravityMean)  \
0                         -0.464761                             -0.018446   
1                         -0.732626                              0.703511   
2                          0.100699                              0.808529   
3                          0.640011                             -0.485366   
4                          0.693578                             -0.615971   
5                          0.275041                             -0.368224   
6                          0.014637                             -0.18951

In [3]:
data['Activity'].value_counts()


LAYING                1407
STANDING              1374
SITTING               1286
WALKING               1226
WALKING_UPSTAIRS      1073
WALKING_DOWNSTAIRS     986
Name: Activity, dtype: int64

In [4]:
# converting activity into numbers

activity_mapping={
"STANDING":0,
"SITTING":1,
"LAYING":2,
"WALKING":3,
"WALKING_DOWNSTAIRS":4,
"WALKING_UPSTAIRS":5
}

# Assuming your dataset has a column named 'activity' containing activity labels
data['activity_code'] = data['Activity'].map(activity_mapping)

data

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  \
0              0.288585          -0.020294          -0.132905   
1              0.278419          -0.016411          -0.123520   
2              0.279653          -0.019467          -0.113462   
3              0.279174          -0.026201          -0.123283   
4              0.276629          -0.016570          -0.115362   
...                 ...                ...                ...   
7347           0.299665          -0.057193          -0.181233   
7348           0.273853          -0.007749          -0.147468   
7349           0.273387          -0.017011          -0.045022   
7350           0.289654          -0.018843          -0.158281   
7351           0.351503          -0.012423          -0.203867   

      tBodyAcc-std()-X  tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  \
0            -0.995279         -0.983111         -0.913526         -0.995112   
1            -0.998245         -0.975300         -0.960322         -0.998807   
2            -0.995380         -0.967187         -0.978944         -0.996520   
3            -0.996091         -0.983403         -0.990675         -0.997099   
4            -0.998139         -0.980817         -0.990482         -0.998321   
...                ...               ...               ...               ...   
7347         -0.195387          0.039905          0.077078         -0.282301   
7348         -0.235309          0.004816          0.059280         -0.322552   
7349         -0.218218         -0.103822          0.274533         -0.304515   
7350         -0.219139         -0.111412          0.268893         -0.310487   
7351         -0.269270         -0.087212          0.177404         -0.377404   

      tBodyAcc-mad()-Y  tBodyAcc-mad()-Z  tBodyAcc-max()-X  ...  \
0            -0.983185         -0.923527         -0.934724  ...   
1            -0.974914         -0.957686         -0.943068  ...   
2            -0.963668         -0.977469         -0.938692  ...   
3            -0.982750         -0.989302         -0.938692  ...   
4            -0.979672         -0.990441         -0.942469  ...   
...                ...               ...               ...  ...   
7347          0.043616          0.060410          0.210795  ...   
7348         -0.029456          0.080585          0.117440  ...   
7349         -0.098913          0.332584          0.043999  ...   
7350         -0.068200          0.319473          0.101702  ...   
7351         -0.038678          0.229430          0.269013  ...   

      angle(tBodyAccMean,gravity)  angle(tBodyAccJerkMean),gravityMean)  \
0                       -0.112754                              0.030400   
1                        0.053477                             -0.007435   
2                       -0.118559                              0.177899   
3                       -0.036788                             -0.012892   
4                        0.123320                              0.122542   
...                           ...                                   ...   
7347                    -0.190437                              0.829718   
7348                     0.064907                              0.875679   
7349                     0.052806                             -0.266724   
7350                    -0.101360                              0.700740   
7351                    -0.280088                             -0.007739   

      angle(tBodyGyroMean,gravityMean)  angle(tBodyGyroJerkMean,gravityMean)  \
0                            -0.464761                             -0.018446   
1                            -0.732626                              0.703511   
2                             0.100699                              0.808529   
3                             0.640011                             -0.485366   
4                             0.693578                             -0.615971   
...                                ...                                   ...  

In [5]:
drop_col=["subject","Activity"]
data.drop(columns=drop_col,axis=1,inplace=True)
data

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  \
0              0.288585          -0.020294          -0.132905   
1              0.278419          -0.016411          -0.123520   
2              0.279653          -0.019467          -0.113462   
3              0.279174          -0.026201          -0.123283   
4              0.276629          -0.016570          -0.115362   
...                 ...                ...                ...   
7347           0.299665          -0.057193          -0.181233   
7348           0.273853          -0.007749          -0.147468   
7349           0.273387          -0.017011          -0.045022   
7350           0.289654          -0.018843          -0.158281   
7351           0.351503          -0.012423          -0.203867   

      tBodyAcc-std()-X  tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  \
0            -0.995279         -0.983111         -0.913526         -0.995112   
1            -0.998245         -0.975300         -0.960322         -0.998807   
2            -0.995380         -0.967187         -0.978944         -0.996520   
3            -0.996091         -0.983403         -0.990675         -0.997099   
4            -0.998139         -0.980817         -0.990482         -0.998321   
...                ...               ...               ...               ...   
7347         -0.195387          0.039905          0.077078         -0.282301   
7348         -0.235309          0.004816          0.059280         -0.322552   
7349         -0.218218         -0.103822          0.274533         -0.304515   
7350         -0.219139         -0.111412          0.268893         -0.310487   
7351         -0.269270         -0.087212          0.177404         -0.377404   

      tBodyAcc-mad()-Y  tBodyAcc-mad()-Z  tBodyAcc-max()-X  ...  \
0            -0.983185         -0.923527         -0.934724  ...   
1            -0.974914         -0.957686         -0.943068  ...   
2            -0.963668         -0.977469         -0.938692  ...   
3            -0.982750         -0.989302         -0.938692  ...   
4            -0.979672         -0.990441         -0.942469  ...   
...                ...               ...               ...  ...   
7347          0.043616          0.060410          0.210795  ...   
7348         -0.029456          0.080585          0.117440  ...   
7349         -0.098913          0.332584          0.043999  ...   
7350         -0.068200          0.319473          0.101702  ...   
7351         -0.038678          0.229430          0.269013  ...   

      fBodyBodyGyroJerkMag-skewness()  fBodyBodyGyroJerkMag-kurtosis()  \
0                           -0.298676                        -0.710304   
1                           -0.595051                        -0.861499   
2                           -0.390748                        -0.760104   
3                           -0.117290                        -0.482845   
4                           -0.351471                        -0.699205   
...                               ...                              ...   
7347                        -0.588433                        -0.880324   
7348                        -0.390738                        -0.680744   
7349                         0.025145                        -0.304029   
7350                         0.063907                        -0.344314   
7351                        -0.387052                        -0.740738   

      angle(tBodyAccMean,gravity)  angle(tBodyAccJerkMean),gravityMean)  \
0                       -0.112754                              0.030400   
1                        0.053477                             -0.007435   
2                       -0.118559                              0.177899   
3                       -0.036788                             -0.012892   
4                        0.123320                              0.122542   
...                           ...                                   ...   
7347                    -0.190437            

In [6]:
 # records of the target variable only , Activity

In [7]:
from sklearn.model_selection import train_test_split

# Handle missing values (if any)
#data.dropna(inplace=True)""

# Encode categorical variables (if any)

# Split the data into features (X) and target (y)
X=data.iloc[:,:-1] # all columns except the target variable 
Y=data.iloc[:,-1] # records of the target variable only , Activity

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)


In [8]:
from sklearn.ensemble import RandomForestClassifier
 
random_forest = RandomForestClassifier(n_estimators=100, random_state=42)
random_forest.fit(X_train, y_train)


RandomForestClassifier(random_state=42)

In [9]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_pred = random_forest.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print(f'Classification Report:\n{report}')
print(f'Confusion Matrix:\n{confusion}')


Accuracy: 0.9768864717878993
Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.95      0.95       276
           1       0.95      0.95      0.95       262
           2       1.00      1.00      1.00       280
           3       1.00      0.99      0.99       247
           4       0.99      0.97      0.98       206
           5       0.97      0.99      0.98       200

    accuracy                           0.98      1471
   macro avg       0.98      0.98      0.98      1471
weighted avg       0.98      0.98      0.98      1471

Confusion Matrix:
[[263  13   0   0   0   0]
 [ 12 250   0   0   0   0]
 [  0   0 280   0   0   0]
 [  0   0   0 245   1   1]
 [  0   0   0   1 200   5]
 [  0   0   0   0   1 199]]


In [ ]:
%time
from sklearn.model_selection import GridSearchCV

param_grid = {'n_estimators': [50, 100, 200, 300, 400],
              'max_depth': [None, 10, 20, 30],
              'min_samples_split': [2, 5, 10, 15, 20]}

grid_search = GridSearchCV(RandomForestClassifier(random_state=42),
                           param_grid, cv=5, n_jobs=-1)
grid_search.fit(X_train, y_train)

random_forest = grid_search.best_estimator_



In [ ]:
y_pred = random_forest.predict(X_test)

# Calculating  accuracy and other relevant metrics
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print(f'Classification Report:\n{report}')
print(f'Confusion Matrix:\n{confusion}')

import pickle

# Serialize (pickle) the model to a file
with open('random_forest.pickle', 'wb') as file:
    pickle.dump(random_forest, file)



In [ ]:
# Importing test data to check the performance of model on unseen data 
data2=pd.read_csv("test.csv")
#data2



In [ ]:
data2=data.iloc[42:43,:-1]
data2

In [ ]:
with open("'random_forest.pickle","rb"):
    r=pickle.load(file)

In [12]:
from sklearn.metrics import roc_curve ,roc_auc_score,auc
from sklearn.preprocessing import label_binarize
from itertools import cycle

In [15]:
y_score=random_forest.predict_proba(X_test)


In [ ]:
Y=label_binarize(Y,classes=[0,1,2,3,4,5])
n_class=Y.shape[1]

In [23]:
fpr, tpr,__= roc_curve(y_test, y_score, pos_label=Y.shape[1])
roc_display = RocCurveDisplay(fpr=fpr, tpr=tpr).plot()

IndexError: tuple index out of range